version: "3.9"

services:
  db:
    image: mysql:8.0.35-debian
    container_name: mysql_prod
    restart: always
    env_file:
      - ./config/prod/.env
    ports:
      - "3307:3306"
    volumes:
      - ./config/prod/mysql_dump:/docker-entrypoint-initdb.d
      - mysql_prod_data:/var/lib/mysql
    networks:
      - backend_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_prod
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./config/prod/virtualhosts/films-luis-daw.api.chickenkiller.com.conf:/etc/apache2/sites-enabled/films-luis-daw.api.chickenkiller.com.conf
    depends_on:
      - db
    networks:
      - backend_network

volumes:
  mysql_prod_data:

networks:
  backend_network:
    driver: bridge
