version: "3.9"

services:
  db:
    image: mysql:8.0.35-debian
    container_name: mysql_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "devuser"
      MYSQL_PASSWORD: "devpassword"
      MYSQL_DATABASE: "films"
    ports:
      - "3306:3306"
    volumes:
      - ./config/dev/mysql_dump:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - backend_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: apache_dev
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./config/dev/virtualhosts/films.api.dev.conf:/etc/apache2/sites-enabled/films.api.dev.conf
    depends_on:
      - db
    networks:
      - backend_network

volumes:
  mysql-data:

networks:
  backend_network:
    driver: bridge
